server:
  port:
    8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Passw0rd@2
    driver-class-name: com.mysql.cj.jdbc.Driver

 # application:
  #  name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update  # or validate/create/create-drop/none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true   # ✅ Registers service using IP instead of hostname
  client:
    register-with-eureka: true   # ✅ Registers this service with Eureka
    fetch-registry: true         # ✅ Fetches registry info from Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/   # ✅ Eureka server location
